# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: general, action: index }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

bet:
  url: /bet.:sf_format
  class: sfDoctrineRoute
  options: { model: BetyoloBet, type: list}
  param: { module: bet, action:index, sf_format: html }
  requirements: { sf_method: GET }

bet_show:
  url:     /bet/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: BetyoloBet, type: object }
  param:   { module: bet, action: show, sf_format: html }
  requirements: { sf_method: GET }

#sf_guard_password:
#  url:   /request_password
#  param: { module: sfGuardAuth, action: password }

transaction_deposit:
  url: /transaction/deposit
  param: {module: transaction, action: deposit}

create_deposit:
  url: /transaction/userdeposit
  param: {module: transaction, action: userdeposit}
